### ISSUE TITLE
csv data format

### ISSUE THREAD

**Issue by evelynmitchell** [samcarlos/WW1-Casualty-TS-Plot#1]
I can't view the csv data, because it looks to have an odd encoding.

**Comment by samcarlos** [comment]
Did you try opening it in R?

Otherwise here's a .rdata file:

https://drive.google.com/file/d/0B9nc4zDDl2T-UHVkelZVS0tUVTQ/view?usp=sharing

**Comment by samcarlos** [comment]
I realized it's NOT a csv file.. its an .rdata file with name of .csv. MY MISTAKE. You should be able to load() it into R with no problem.

**Comment by evelynmitchell** [comment]
Thanks!
